import { FlatCompat } from "@eslint/eslintrc";
import { boundaryRules, baseRules } from "@cyberpulse/config/eslint";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  baseRules,
  ...boundaryRules,
  {
    rules: {
      // engineering/logging-monitoring.md §5: console.* is an ESLint error in
      // application code — the logger is the only path, so redaction can't be skipped.
      "no-console": "error",
    },
  },
  // next-env.d.ts is regenerated by `next dev`/`next build` and must not be
  // hand-edited — Next's own scaffolding excludes it from lint the same way.
  // public/maplibre-gl-*.mjs are vendored copies of maplibre-gl's own dist/
  // worker build (components/map/MapCanvas.tsx), not source this repo owns.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts", "public/maplibre-gl-worker.mjs", "public/maplibre-gl-shared.mjs"] },
];

export default config;
