# GENERATED FILE — do not edit by hand.
# Source: packages/shared/schemas/error.schema.json — regenerate with `pnpm generate:pydantic`.
# generated by datamodel-codegen:
#   filename:  error.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Literal[
        'VALIDATION_ERROR',
        'UNAUTHORIZED',
        'FORBIDDEN',
        'NOT_FOUND',
        'INVALID_TRANSITION',
        'CONFLICT',
        'RATE_LIMITED',
        'INTERNAL_ERROR',
        'ML_UNAVAILABLE',
        'TIMEOUT',
    ]
    message: str = Field(..., min_length=1)
    field: str | None = None
    requestId: str = Field(..., min_length=1)


class ErrorEnvelope(BaseModel):
    """
    The single error shape returned by every endpoint (ADR-020, architecture/api-design.md §1.2).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    error: Error
