# GENERATED FILE — do not edit by hand.
# Source: packages/shared/schemas/health.schema.json — regenerate with `pnpm generate:pydantic`.
# generated by datamodel-codegen:
#   filename:  health.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Web(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['up', 'degraded', 'down']
    latencyMs: float = Field(..., ge=0.0)


class Database(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['up', 'degraded', 'down']
    latencyMs: float = Field(..., ge=0.0)


class MlService(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['up', 'degraded', 'down']
    latencyMs: float = Field(..., ge=0.0)
    modelVersion: str | None = None
    modelLoaded: bool


class HealthResponse(BaseModel):
    """
    GET /api/health (architecture/api-design.md API-080). Composes web, database and ML status; never throws.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['healthy', 'degraded', 'unhealthy']
    web: Web
    database: Database
    mlService: MlService
    checkedAt: AwareDatetime
