# GENERATED FILE — do not edit by hand.
# Source: packages/shared/schemas/ml-health.schema.json — regenerate with `pnpm generate:pydantic`.
# generated by datamodel-codegen:
#   filename:  ml-health.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict


class MlHealthResponse(BaseModel):
    """
    GET /health on the ML service (architecture/api-design.md ML-003). Validated on arrival by the web app's ML client — a malformed response becomes a typed error, never a database row (RULE-backend.md).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['healthy', 'degraded', 'unhealthy']
    modelLoaded: bool
    modelVersion: str | None
    featureSchemaVersion: str | None
    loadedAt: AwareDatetime | None = None
