# GENERATED FILE — do not edit by hand.
# Source: packages/shared/schemas/ml-predict-request.schema.json — regenerate with `pnpm generate:pydantic`.
# generated by datamodel-codegen:
#   filename:  ml-predict-request.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class Complaint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    complaintId: str = Field(..., pattern='^C-[0-9]{5}$')
    fraudType: Literal[
        'UPI_FRAUD', 'INVESTMENT_SCAM', 'PHISHING', 'JOB_SCAM', 'QR_FRAUD', 'CARD_FRAUD'
    ]
    amountPaise: int = Field(..., ge=1)
    timestamp: AwareDatetime
    victimLat: float = Field(..., ge=6.0, le=37.5)
    victimLon: float = Field(..., ge=68.0, le=97.5)
    victimH3R8: str = Field(..., min_length=1)


class Transaction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amountPaise: int = Field(..., ge=1)
    timestamp: AwareDatetime
    channel: Literal['UPI', 'IMPS', 'NEFT', 'RTGS', 'CARD', 'ATM', 'WALLET']
    hopIndex: int = Field(..., ge=0)
    riskIndicator: Literal['NONE', 'LOW', 'MEDIUM', 'HIGH']


class Account(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accountId: str = Field(..., pattern='^ACC-[0-9]{8}$')
    accountType: Literal['VICTIM', 'MULE', 'SUSPICIOUS', 'MERCHANT', 'NORMAL']
    openedAt: AwareDatetime
    riskScore: float = Field(..., ge=0.0, le=1.0)
    priorSuspiciousFlags: int = Field(..., ge=0)
    priorWithdrawalCount: int = Field(..., ge=0)


class CandidateCell(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    h3Index: str = Field(..., min_length=1)
    lat: float
    lon: float
    atmCount: int = Field(..., ge=0)
    atmDensity: float = Field(..., ge=0.0)
    historicalHotspotScore: float = Field(..., ge=0.0, le=1.0)
    withdrawalCount: int = Field(..., ge=0)
    name: str = Field(..., min_length=1)
    district: str = Field(..., min_length=1)
    state: str = Field(..., min_length=1)


class Thresholds(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    high: float = Field(..., ge=0.0, le=1.0)
    medium: float = Field(..., ge=0.0, le=1.0)


class MlPredictRequest(BaseModel):
    """
    POST /predict request body, ML service (architecture/api-design.md ML-001). The web application supplies everything; the service reads no database (RULE-security.md 'The ML boundary').
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    requestId: str = Field(..., min_length=1)
    complaint: Complaint
    transactions: list[Transaction]
    accounts: list[Account]
    candidateCells: list[CandidateCell] = Field(..., max_length=60, min_length=1)
    thresholds: Thresholds | None = None
    topK: int | None = Field(5, ge=1, le=20)
