# GENERATED FILE — do not edit by hand.
# Source: packages/shared/schemas/ml-predict-response.schema.json — regenerate with `pnpm generate:pydantic`.
# generated by datamodel-codegen:
#   filename:  ml-predict-response.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class PredictedLocation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    h3Index: str
    lat: float
    lon: float
    district: str
    state: str


class ExpectedWindow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: AwareDatetime
    end: AwareDatetime
    confidence: Literal['LOW', 'MEDIUM', 'HIGH']
    fallback: bool


class RankedHotspot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    rank: int = Field(..., ge=1)
    name: str
    h3Index: str
    lat: float
    lon: float
    score: float = Field(..., ge=0.0, le=1.0)
    likelyAtms: int = Field(..., ge=0)


class Factor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: Literal[
        'Transaction Velocity',
        'Historical Hotspot',
        'Linked Account Pattern',
        'ATM Proximity',
        'Time Pattern',
        'Amount / Frequency',
        'Account Age',
        'Withdrawal History',
        'Other factors',
    ]
    contribution: float = Field(..., ge=-100.0, le=100.0)
    direction: Literal['INCREASES', 'REDUCES']


class PipelineStage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    durationMs: int = Field(..., ge=0)


class MlPredictResponse(BaseModel):
    """
    POST /predict 200 response, ML service (architecture/api-design.md ML-001) — the prediction object of API-010 minus the persistence fields (predictionRef, createdAt) and minus estimatedExposurePaise (computed by predictionService from complaints data the DB-less ML service cannot read, architecture/low-level-design.md §3.1), plus pipelineStages.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    complaintId: str = Field(..., pattern='^C-[0-9]{5}$')
    riskScore: float = Field(..., ge=0.0, le=1.0)
    riskLevel: Literal['LOW', 'MEDIUM', 'HIGH']
    confidence: Literal['LOW', 'MEDIUM', 'HIGH']
    predictedLocation: PredictedLocation
    expectedWindow: ExpectedWindow
    likelyAtms: int = Field(..., ge=0)
    rankedHotspots: list[RankedHotspot] = Field(..., max_length=20, min_length=1)
    factors: list[Factor]
    explanationAvailable: bool
    clusteringFallback: bool
    modelVersion: str
    featureSchemaVersion: str
    inferenceMs: int | None = Field(None, ge=0)
    pipelineStages: list[PipelineStage]
