# GENERATED FILE — do not edit by hand.
# Source: packages/shared/schemas/predict-request.schema.json — regenerate with `pnpm generate:pydantic`.
# generated by datamodel-codegen:
#   filename:  predict-request.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class PredictRequest(BaseModel):
    """
    POST /api/predict request body (architecture/api-design.md API-010).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    complaintId: str = Field(..., pattern='^C-[0-9]{5}$')
    topK: int | None = Field(5, ge=1, le=20)
    forceRefresh: bool | None = False
